# Generated by Django 4.2.1 on 2023-06-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='laptopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('company_name', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=10)),
                ('rom', models.CharField(max_length=10)),
                ('model_name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
